name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.14.0

    - name: Check Zig formatting
      run: zig fmt --check src/

    - name: Run tests
      run: zig build test

    - name: Build CLI
      run: zig build

    - name: Build library
      run: zig build lib