name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build for ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Linux
          - os: ubuntu-latest
            platform: linux-x86_64
            target: x86_64-linux
            artifact_name: litholog
            asset_name: litholog-linux-x86_64
          - os: ubuntu-latest
            platform: linux-aarch64
            target: aarch64-linux
            artifact_name: litholog
            asset_name: litholog-linux-aarch64
          
          # Windows
          - os: windows-latest
            platform: windows-x86_64
            target: x86_64-windows
            artifact_name: litholog.exe
            asset_name: litholog-windows-x86_64.exe
          
          # macOS
          - os: macos-latest
            platform: macos-x86_64
            target: x86_64-macos
            artifact_name: litholog
            asset_name: litholog-macos-x86_64
          - os: macos-latest
            platform: macos-aarch64
            target: aarch64-macos
            artifact_name: litholog
            asset_name: litholog-macos-aarch64

    steps:
    - uses: actions/checkout@v4

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.14.0

    - name: Extract version from tag
      id: version
      shell: bash
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "Extracted version: $VERSION"

    - name: Build binary
      run: |
        zig build -Dtarget=${{ matrix.target }} -Doptimize=ReleaseFast

    - name: Prepare artifact
      shell: bash
      run: |
        cp zig-out/bin/${{ matrix.artifact_name }} ${{ matrix.asset_name }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.asset_name }}
        path: ${{ matrix.asset_name }}
        retention-days: 5

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4

    - name: Extract version from tag
      id: version
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Display structure of downloaded files
      run: ls -la artifacts/

    - name: Create Release and Upload Assets
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Create release with GitHub CLI
        gh release create ${{ github.ref_name }} \
          --title "Litholog ${{ steps.version.outputs.VERSION }}" \
          --notes "# Litholog ${{ steps.version.outputs.VERSION }}
        
        A geological description parser CLI tool following BS5930 standards.
        
        ## Installation
        
        ### Linux/macOS
        \`\`\`bash
        # Download the appropriate binary for your platform
        curl -L https://github.com/${{ github.repository }}/releases/download/v${{ steps.version.outputs.VERSION }}/litholog-linux-x86_64 -o litholog
        chmod +x litholog
        sudo mv litholog /usr/local/bin/
        \`\`\`
        
        ### Windows
        Download the Windows executable and add it to your PATH.
        
        ## Usage
        
        \`\`\`bash
        # Parse a geological description
        litholog \"Firm CLAY\"
        
        # Interactive mode
        litholog
        
        # Show help
        litholog --help
        \`\`\`
        
        ## Features
        
        - Parse geological descriptions according to BS5930 standards
        - Extract material types, consistency, density, and other properties
        - Support for both soil and rock descriptions
        - Interactive TUI mode for exploring geological data
        - JSON output for integration with other tools
        
        ## Platform Support
        
        This release includes binaries for:
        - Linux (x86_64, aarch64)
        - Windows (x86_64)
        - macOS (x86_64, aarch64/Apple Silicon)
        
        ## What's Changed
        
        See the commit history for detailed changes in this release."
        
        # Upload all assets
        gh release upload ${{ github.ref_name }} \
          artifacts/litholog-linux-x86_64/litholog-linux-x86_64 \
          artifacts/litholog-linux-aarch64/litholog-linux-aarch64 \
          artifacts/litholog-windows-x86_64.exe/litholog-windows-x86_64.exe \
          artifacts/litholog-macos-x86_64/litholog-macos-x86_64 \
          artifacts/litholog-macos-aarch64/litholog-macos-aarch64
